stages:
  - test
  - docker-build 

build:
  stage: docker-build
  image: docker:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "devel"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build --tag $CI_REGISTRY_IMAGE:devel --file Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:devel
  tags:
    - docker-build

include:
    - template: Jobs/Secret-Detection.gitlab-ci.yml
