stages:
  - test
  - docker-build 

build:
  stage: docker-build
  image: docker:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "devel"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build --tag $CI_REGISTRY_IMAGE:devel --file Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:devel
  tags:
    - docker-build

include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml

security-check:
  stage: test
  artifacts:
    paths:
      - gl-container-scanning-report.json
      - gl-sast-report.json
      - gl-secret-detection-report.json


