stages:
  - docker-build
  - deploy_docs
  - test

build:
  stage: docker-build
  image: docker:latest
  rules:
    - if: $CI_COMMIT_BRANCH == "devel"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build --tag $CI_REGISTRY_IMAGE:devel --file Dockerfile .
    - docker push $CI_REGISTRY_IMAGE:devel
  tags:
    - docker-build

pages:
  stage: deploy_docs
  image: python:3.8-buster
  script:
    - pip install mkdocs-material
    - mkdocs build --strict --verbose
  artifacts:
    paths:
      - public


include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml

sast:
  stage: test

container_scanning:
  variables:
    CS_IMAGE: docker.io/nexryai/frea:devel

