version: '3'

services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    networks:
      - frea
    environment:
      POSTGRES_DB: freasearch
      POSTGRES_USER: freasearch
      POSTGRES_PASSWORD: freasearch
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID

  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    command: redis-server --save "" --appendonly "no" --protected-mode "no"
    networks:
      - frea
    tmpfs:
      - /var/lib/redis
      - /var/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE

  frea:
    container_name: frea
    image: nexryai/frea:devel
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - frea
    environment:
      POSTGRESQL_HOST: db
      POSTGRESQL_USER: freasearch
      POSTGRESQL_PASSWORD: freasearch
      COUNT_USERS: "true"
      TZ: Asia/Tokyo
    ports:
     - "127.0.0.1:8888:8888"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    volumes:
      - /etc/localtime:/etc/localtime:ro
        
networks:
  frea:
