# SearXNG settings

use_default_settings: true

general:
  debug: false


search:
  # Filter results. 0: None, 1: Moderate, 2: Strict
  safe_search: 1

  # Default search language - leave blank to detect from browser information or
  # use codes from 'languages.py'
  default_lang: ''

  # remove format to deny access, use lower case.
  formats:
    - html
    - json

server:
  secret_key: "ultrasecretkey"  # change this!
  
  # Proxying image results through SearXNG
  image_proxy: false

